[
    {
      "date": "2023-08-15",
      "pass_completion_percent": 87,
      "goals_scored": 2,
      "assists": 1,
      "minutes_played": 90,
      "shots_on_goal": 4,
      "shots_off_target": 1,
      "tackles": 3,
      "interceptions": 2,
      "fouls_committed": 2,
      "fouls_received": 3,
      "yellow_cards": 0,
      "red_cards": 0,
      "saves": 0
    },
    {
      "date": "2023-08-23",
      "pass_completion_percent": 88,
      "goals_scored": 1,
      "assists": 0,
      "minutes_played": 85,
      "shots_on_goal": 2,
      "shots_off_target": 2,
      "tackles": 4,
      "interceptions": 3,
      "fouls_committed": 1,
      "fouls_received": 2,
      "yellow_cards": 1,
      "red_cards": 0,
      "saves": 0
    },
    {
      "date": "2023-09-02",
      "pass_completion_percent": 85,
      "goals_scored": 0,
      "assists": 2,
      "minutes_played": 90,
      "shots_on_goal": 1,
      "shots_off_target": 0,
      "tackles": 2,
      "interceptions": 3,
      "fouls_committed": 3,
      "fouls_received": 1,
      "yellow_cards": 0,
      "red_cards": 0,
      "saves": 0
    },
    {
      "date": "2023-09-10",
      "pass_completion_percent": 90,
      "goals_scored": 1,
      "assists": 1,
      "minutes_played": 90,
      "shots_on_goal": 3,
      "shots_off_target": 1,
      "tackles": 3,
      "interceptions": 2,
      "fouls_committed": 1,
      "fouls_received": 2,
      "yellow_cards": 0,
      "red_cards": 0,
      "saves": 0
    },
    {
      "date": "2023-09-17",
      "pass_completion_percent": 88,
      "goals_scored": 0,
      "assists": 0,
      "minutes_played": 80,
      "shots_on_goal": 2,
      "shots_off_target": 3,
      "tackles": 2,
      "interceptions": 4,
      "fouls_committed": 2,
      "fouls_received": 3,
      "yellow_cards": 0,
      "red_cards": 0,
      "saves": 0
    },
    {
      "date": "2023-09-25",
      "pass_completion_percent": 89,
      "goals_scored": 1,
      "assists": 1,
      "minutes_played": 85,
      "shots_on_goal": 3,
      "shots_off_target": 1,
      "tackles": 3,
      "interceptions": 3,
      "fouls_committed": 2,
      "fouls_received": 1,
      "yellow_cards": 0,
      "red_cards": 0,
      "saves": 0
    }
    // Add more match objects as needed
  ]
  